# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default
  # vmImage: 'ubuntu-latest'

steps:
- task: UnityBuildTask@3
  displayName: Unity Build
  inputs:
    buildTarget: 'WebGL'
    unityProjectPath: "Game"
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/drop'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.BuildId)'
    publishLocation: 'Container'
